drop extension if exists "pg_net";

create sequence "public"."productos_codigo_seq";


  create table "public"."categorias_productos" (
    "id" uuid not null default gen_random_uuid(),
    "nombre" text not null
      );


alter table "public"."categorias_productos" enable row level security;


  create table "public"."categorias_proveedor" (
    "id" uuid not null default gen_random_uuid(),
    "nombre" text not null
      );


alter table "public"."categorias_proveedor" enable row level security;


  create table "public"."conceptos_factura" (
    "id" uuid not null default gen_random_uuid(),
    "empresa_id" uuid not null,
    "nombre" text not null,
    "tipo" text not null,
    "activo" boolean not null default true,
    "orden" integer not null default 0,
    "requiere_afip" boolean not null default false,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "afecta_costo" boolean not null default true
      );



  create table "public"."empresas" (
    "id" uuid not null default gen_random_uuid(),
    "razon_social" text not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."empresas" enable row level security;


  create table "public"."factura_cargos" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."factura_cargos" enable row level security;


  create table "public"."factura_conceptos" (
    "id" uuid not null default gen_random_uuid(),
    "factura_id" uuid not null,
    "concepto_id" uuid not null,
    "descripcion" text,
    "importe" numeric(14,2) not null default 0,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );



  create table "public"."factura_impuestos" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."factura_impuestos" enable row level security;


  create table "public"."factura_items" (
    "id" uuid not null default gen_random_uuid(),
    "factura_id" uuid,
    "producto_id" uuid,
    "cantidad" numeric(12,2),
    "precio_unitario" numeric(12,2),
    "iva" numeric,
    "alicuota IVA" numeric,
    "descuento" numeric not null default 0,
    "precio_final" numeric default '0'::numeric,
    "precio_bruto_unitario" numeric,
    "descuento_importe" numeric default 0,
    "bonificacion_importe" numeric default 0,
    "precio_neto_unitario" numeric,
    "subtotal_neto" numeric,
    "iva_importe" numeric default 0,
    "impuestos_internos" numeric default 0,
    "descuentos_detalle" jsonb,
    "bonificacion_tipo" text,
    "cantidad_bonificada" numeric default 0
      );


alter table "public"."factura_items" enable row level security;


  create table "public"."facturas" (
    "id" uuid not null default gen_random_uuid(),
    "proveedor_id" uuid,
    "empresa_id" uuid,
    "fecha" date not null,
    "numero" text,
    "subtotal" numeric(12,2),
    "iva" numeric(12,2),
    "iibb" numeric(12,2),
    "total" numeric(12,2) not null,
    "fecha_vencimiento" date,
    "estado" text default 'pendiente'::text,
    "archivo_url" text,
    "created_at" timestamp with time zone default now(),
    "tipo_comprobante" text,
    "estado_documento" text default 'Registrada'::text,
    "estado_pago" text default 'Pendiente'::text,
    "iva_21" numeric(12,2) default 0,
    "iva_105" numeric(12,2) default 0,
    "iva_27" numeric(12,2) default 0,
    "iva_exento" numeric(12,2) default 0,
    "percepcion_iibb_caba" numeric(12,2) default 0,
    "percepcion_iibb_bsas" numeric(12,2) default 0,
    "otros_impuestos" numeric(12,2) default 0,
    "otros_cargos" numeric(12,2) default 0,
    "confianza_ia" numeric(5,2),
    "subtotal_bruto" numeric,
    "descuento_total" numeric default 0,
    "subtotal_neto" numeric,
    "impuestos_internos" numeric default 0,
    "percepcion_iva" numeric default 0
      );


alter table "public"."facturas" enable row level security;


  create table "public"."formas_pago" (
    "id" uuid not null default gen_random_uuid(),
    "nombre" text not null
      );


alter table "public"."formas_pago" enable row level security;


  create table "public"."ia_procesamientos" (
    "id" uuid not null default gen_random_uuid(),
    "factura_id" uuid,
    "proveedor_ia" text not null,
    "ia_secundaria" text,
    "estado" text not null default 'procesando'::text,
    "motivo_error" text,
    "accion_usuario" text,
    "lineas_detectadas" integer,
    "iniciado_en" timestamp with time zone not null default now(),
    "finalizado_en" timestamp with time zone,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."ia_procesamientos" enable row level security;


  create table "public"."pagos" (
    "id" uuid not null default gen_random_uuid(),
    "factura_id" uuid,
    "remito_id" uuid,
    "forma_pago_id" uuid,
    "fecha" date not null,
    "monto" numeric(12,2) not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."pagos" enable row level security;


  create table "public"."producto_aliases" (
    "id" uuid not null default gen_random_uuid(),
    "proveedor_id" uuid not null,
    "producto_id" uuid not null,
    "codigo_proveedor" text,
    "descripcion_original" text not null,
    "descripcion_normalizada" text not null,
    "confianza" integer not null default 100,
    "veces_usado" integer not null default 1,
    "ultima_fecha" timestamp with time zone default now(),
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );



  create table "public"."productos" (
    "id" uuid not null default gen_random_uuid(),
    "nombre" text not null,
    "unidad_medida" text,
    "categoria_id" uuid,
    "created_at" timestamp with time zone default now(),
    "costo_actual" numeric,
    "activo" boolean,
    "ultimo_costo" numeric,
    "precio_venta" numeric,
    "codigo" text default public.generar_codigo_producto()
      );


alter table "public"."productos" enable row level security;


  create table "public"."proveedores" (
    "id" uuid not null default gen_random_uuid(),
    "nombre_fantasia" text not null,
    "cuit" text,
    "telefono" text,
    "email" text,
    "categoria_id" uuid,
    "etiqueta_1" text,
    "etiqueta_2" text,
    "created_at" timestamp with time zone default now(),
    "razon_social" text,
    "activo" boolean,
    "condicion_pago" text,
    "condicion_iva" text,
    "iibb_bsas" numeric(5,2) default 0,
    "iibb_caba" numeric(5,2) default 0,
    "otros_cargos" text
      );


alter table "public"."proveedores" enable row level security;


  create table "public"."remito_items" (
    "id" uuid not null default gen_random_uuid(),
    "remito_id" uuid,
    "producto_id" uuid,
    "cantidad" numeric(12,2),
    "precio_unitario" numeric(12,2),
    "descuento" numeric not null default 0,
    "precio_final" numeric,
    "precio_bruto_unitario" numeric,
    "descuento_importe" numeric not null default 0,
    "bonificacion_importe" numeric not null default 0,
    "precio_neto_unitario" numeric,
    "subtotal_neto" numeric,
    "descuentos_detalle" jsonb,
    "bonificacion_tipo" text,
    "cantidad_bonificada" numeric
      );


alter table "public"."remito_items" enable row level security;


  create table "public"."remitos" (
    "id" uuid not null default gen_random_uuid(),
    "proveedor_id" uuid,
    "empresa_id" uuid,
    "fecha" date not null,
    "numero" text,
    "monto_total" numeric(12,2) not null,
    "fecha_vencimiento" date,
    "estado" text default 'pendiente'::text,
    "archivo_url" text,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."remitos" enable row level security;

CREATE UNIQUE INDEX categorias_productos_pkey ON public.categorias_productos USING btree (id);

CREATE UNIQUE INDEX categorias_proveedor_pkey ON public.categorias_proveedor USING btree (id);

CREATE UNIQUE INDEX conceptos_factura_empresa_id_nombre_key ON public.conceptos_factura USING btree (empresa_id, nombre);

CREATE UNIQUE INDEX conceptos_factura_pkey ON public.conceptos_factura USING btree (id);

CREATE UNIQUE INDEX empresas_pkey ON public.empresas USING btree (id);

CREATE UNIQUE INDEX factura_cargos_pkey ON public.factura_cargos USING btree (id);

CREATE UNIQUE INDEX factura_conceptos_pkey ON public.factura_conceptos USING btree (id);

CREATE UNIQUE INDEX factura_impuestos_pkey ON public.factura_impuestos USING btree (id);

CREATE UNIQUE INDEX factura_items_pkey ON public.factura_items USING btree (id);

CREATE UNIQUE INDEX facturas_pkey ON public.facturas USING btree (id);

CREATE UNIQUE INDEX formas_pago_pkey ON public.formas_pago USING btree (id);

CREATE UNIQUE INDEX ia_procesamientos_pkey ON public.ia_procesamientos USING btree (id);

CREATE INDEX idx_alias_codigo ON public.producto_aliases USING btree (codigo_proveedor);

CREATE INDEX idx_alias_normalizada ON public.producto_aliases USING btree (descripcion_normalizada);

CREATE INDEX idx_alias_producto ON public.producto_aliases USING btree (producto_id);

CREATE INDEX idx_alias_proveedor ON public.producto_aliases USING btree (proveedor_id);

CREATE INDEX idx_conceptos_empresa ON public.conceptos_factura USING btree (empresa_id);

CREATE INDEX idx_conceptos_tipo ON public.conceptos_factura USING btree (tipo);

CREATE INDEX idx_factura_conceptos_concepto ON public.factura_conceptos USING btree (concepto_id);

CREATE INDEX idx_factura_conceptos_factura ON public.factura_conceptos USING btree (factura_id);

CREATE INDEX idx_ia_procesamientos_created_at ON public.ia_procesamientos USING btree (created_at DESC);

CREATE INDEX idx_ia_procesamientos_factura_id ON public.ia_procesamientos USING btree (factura_id);

CREATE UNIQUE INDEX pagos_pkey ON public.pagos USING btree (id);

CREATE UNIQUE INDEX producto_aliases_pkey ON public.producto_aliases USING btree (id);

CREATE UNIQUE INDEX productos_codigo_unique ON public.productos USING btree (codigo);

CREATE UNIQUE INDEX productos_nombre_unique ON public.productos USING btree (nombre);

CREATE UNIQUE INDEX productos_pkey ON public.productos USING btree (id);

CREATE UNIQUE INDEX proveedores_pkey ON public.proveedores USING btree (id);

CREATE UNIQUE INDEX remito_items_pkey ON public.remito_items USING btree (id);

CREATE UNIQUE INDEX remitos_pkey ON public.remitos USING btree (id);

alter table "public"."categorias_productos" add constraint "categorias_productos_pkey" PRIMARY KEY using index "categorias_productos_pkey";

alter table "public"."categorias_proveedor" add constraint "categorias_proveedor_pkey" PRIMARY KEY using index "categorias_proveedor_pkey";

alter table "public"."conceptos_factura" add constraint "conceptos_factura_pkey" PRIMARY KEY using index "conceptos_factura_pkey";

alter table "public"."empresas" add constraint "empresas_pkey" PRIMARY KEY using index "empresas_pkey";

alter table "public"."factura_cargos" add constraint "factura_cargos_pkey" PRIMARY KEY using index "factura_cargos_pkey";

alter table "public"."factura_conceptos" add constraint "factura_conceptos_pkey" PRIMARY KEY using index "factura_conceptos_pkey";

alter table "public"."factura_impuestos" add constraint "factura_impuestos_pkey" PRIMARY KEY using index "factura_impuestos_pkey";

alter table "public"."factura_items" add constraint "factura_items_pkey" PRIMARY KEY using index "factura_items_pkey";

alter table "public"."facturas" add constraint "facturas_pkey" PRIMARY KEY using index "facturas_pkey";

alter table "public"."formas_pago" add constraint "formas_pago_pkey" PRIMARY KEY using index "formas_pago_pkey";

alter table "public"."ia_procesamientos" add constraint "ia_procesamientos_pkey" PRIMARY KEY using index "ia_procesamientos_pkey";

alter table "public"."pagos" add constraint "pagos_pkey" PRIMARY KEY using index "pagos_pkey";

alter table "public"."producto_aliases" add constraint "producto_aliases_pkey" PRIMARY KEY using index "producto_aliases_pkey";

alter table "public"."productos" add constraint "productos_pkey" PRIMARY KEY using index "productos_pkey";

alter table "public"."proveedores" add constraint "proveedores_pkey" PRIMARY KEY using index "proveedores_pkey";

alter table "public"."remito_items" add constraint "remito_items_pkey" PRIMARY KEY using index "remito_items_pkey";

alter table "public"."remitos" add constraint "remitos_pkey" PRIMARY KEY using index "remitos_pkey";

alter table "public"."conceptos_factura" add constraint "conceptos_factura_empresa_id_fkey" FOREIGN KEY (empresa_id) REFERENCES public.empresas(id) ON DELETE CASCADE not valid;

alter table "public"."conceptos_factura" validate constraint "conceptos_factura_empresa_id_fkey";

alter table "public"."conceptos_factura" add constraint "conceptos_factura_empresa_id_nombre_key" UNIQUE using index "conceptos_factura_empresa_id_nombre_key";

alter table "public"."conceptos_factura" add constraint "conceptos_factura_tipo_check" CHECK ((tipo = ANY (ARRAY['IMPUESTO'::text, 'CARGO'::text, 'DESCUENTO'::text]))) not valid;

alter table "public"."conceptos_factura" validate constraint "conceptos_factura_tipo_check";

alter table "public"."factura_conceptos" add constraint "factura_conceptos_concepto_id_fkey" FOREIGN KEY (concepto_id) REFERENCES public.conceptos_factura(id) not valid;

alter table "public"."factura_conceptos" validate constraint "factura_conceptos_concepto_id_fkey";

alter table "public"."factura_conceptos" add constraint "factura_conceptos_factura_id_fkey" FOREIGN KEY (factura_id) REFERENCES public.facturas(id) ON DELETE CASCADE not valid;

alter table "public"."factura_conceptos" validate constraint "factura_conceptos_factura_id_fkey";

alter table "public"."factura_items" add constraint "factura_items_factura_id_fkey" FOREIGN KEY (factura_id) REFERENCES public.facturas(id) ON DELETE CASCADE not valid;

alter table "public"."factura_items" validate constraint "factura_items_factura_id_fkey";

alter table "public"."factura_items" add constraint "factura_items_producto_id_fkey" FOREIGN KEY (producto_id) REFERENCES public.productos(id) not valid;

alter table "public"."factura_items" validate constraint "factura_items_producto_id_fkey";

alter table "public"."facturas" add constraint "facturas_empresa_id_fkey" FOREIGN KEY (empresa_id) REFERENCES public.empresas(id) not valid;

alter table "public"."facturas" validate constraint "facturas_empresa_id_fkey";

alter table "public"."facturas" add constraint "facturas_proveedor_id_fkey" FOREIGN KEY (proveedor_id) REFERENCES public.proveedores(id) not valid;

alter table "public"."facturas" validate constraint "facturas_proveedor_id_fkey";

alter table "public"."ia_procesamientos" add constraint "ia_procesamientos_factura_id_fkey" FOREIGN KEY (factura_id) REFERENCES public.facturas(id) ON DELETE SET NULL not valid;

alter table "public"."ia_procesamientos" validate constraint "ia_procesamientos_factura_id_fkey";

alter table "public"."pagos" add constraint "pagos_factura_id_fkey" FOREIGN KEY (factura_id) REFERENCES public.facturas(id) not valid;

alter table "public"."pagos" validate constraint "pagos_factura_id_fkey";

alter table "public"."pagos" add constraint "pagos_forma_pago_id_fkey" FOREIGN KEY (forma_pago_id) REFERENCES public.formas_pago(id) not valid;

alter table "public"."pagos" validate constraint "pagos_forma_pago_id_fkey";

alter table "public"."pagos" add constraint "pagos_remito_id_fkey" FOREIGN KEY (remito_id) REFERENCES public.remitos(id) not valid;

alter table "public"."pagos" validate constraint "pagos_remito_id_fkey";

alter table "public"."producto_aliases" add constraint "producto_aliases_producto_id_fkey" FOREIGN KEY (producto_id) REFERENCES public.productos(id) not valid;

alter table "public"."producto_aliases" validate constraint "producto_aliases_producto_id_fkey";

alter table "public"."producto_aliases" add constraint "producto_aliases_proveedor_id_fkey" FOREIGN KEY (proveedor_id) REFERENCES public.proveedores(id) not valid;

alter table "public"."producto_aliases" validate constraint "producto_aliases_proveedor_id_fkey";

alter table "public"."productos" add constraint "productos_categoria_id_fkey" FOREIGN KEY (categoria_id) REFERENCES public.categorias_productos(id) not valid;

alter table "public"."productos" validate constraint "productos_categoria_id_fkey";

alter table "public"."productos" add constraint "productos_codigo_unique" UNIQUE using index "productos_codigo_unique";

alter table "public"."productos" add constraint "productos_nombre_unique" UNIQUE using index "productos_nombre_unique";

alter table "public"."proveedores" add constraint "proveedores_categoria_id_fkey" FOREIGN KEY (categoria_id) REFERENCES public.categorias_proveedor(id) not valid;

alter table "public"."proveedores" validate constraint "proveedores_categoria_id_fkey";

alter table "public"."remito_items" add constraint "remito_items_producto_id_fkey" FOREIGN KEY (producto_id) REFERENCES public.productos(id) not valid;

alter table "public"."remito_items" validate constraint "remito_items_producto_id_fkey";

alter table "public"."remito_items" add constraint "remito_items_remito_id_fkey" FOREIGN KEY (remito_id) REFERENCES public.remitos(id) ON DELETE CASCADE not valid;

alter table "public"."remito_items" validate constraint "remito_items_remito_id_fkey";

alter table "public"."remitos" add constraint "remitos_empresa_id_fkey" FOREIGN KEY (empresa_id) REFERENCES public.empresas(id) not valid;

alter table "public"."remitos" validate constraint "remitos_empresa_id_fkey";

alter table "public"."remitos" add constraint "remitos_proveedor_id_fkey" FOREIGN KEY (proveedor_id) REFERENCES public.proveedores(id) not valid;

alter table "public"."remitos" validate constraint "remitos_proveedor_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.generar_codigo_producto()
 RETURNS text
 LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN 'PR' || LPAD(nextval('productos_codigo_seq')::TEXT, 4, '0');
END;
$function$
;

CREATE OR REPLACE FUNCTION public.guardar_alias(p_proveedor_id uuid, p_producto_id uuid, p_codigo_proveedor text, p_descripcion_original text, p_descripcion_normalizada text, p_confianza integer DEFAULT 100)
 RETURNS uuid
 LANGUAGE plpgsql
AS $function$
declare

    v_alias_id uuid;

begin

    select id
    into v_alias_id
    from producto_aliases
    where proveedor_id = p_proveedor_id
      and descripcion_normalizada = p_descripcion_normalizada
    limit 1;

    if v_alias_id is not null then

        update producto_aliases
        set
            producto_id = p_producto_id,
            codigo_proveedor = p_codigo_proveedor,
            confianza = p_confianza,
            updated_at = now()
        where id = v_alias_id;

        return v_alias_id;

    end if;

    insert into producto_aliases(

        proveedor_id,

        producto_id,

        codigo_proveedor,

        descripcion_original,

        descripcion_normalizada,

        confianza

    )

    values(

        p_proveedor_id,

        p_producto_id,

        p_codigo_proveedor,

        p_descripcion_original,

        p_descripcion_normalizada,

        p_confianza

    )

    returning id
    into v_alias_id;

    return v_alias_id;

end;
$function$
;

CREATE OR REPLACE FUNCTION public.incrementar_uso_alias(p_alias_id uuid)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
begin

    update producto_aliases
    set
        veces_usado = veces_usado + 1,
        ultima_fecha = now(),
        updated_at = now()
    where id = p_alias_id;

end;
$function$
;

grant delete on table "public"."categorias_productos" to "anon";

grant insert on table "public"."categorias_productos" to "anon";

grant references on table "public"."categorias_productos" to "anon";

grant select on table "public"."categorias_productos" to "anon";

grant trigger on table "public"."categorias_productos" to "anon";

grant truncate on table "public"."categorias_productos" to "anon";

grant update on table "public"."categorias_productos" to "anon";

grant delete on table "public"."categorias_productos" to "authenticated";

grant insert on table "public"."categorias_productos" to "authenticated";

grant references on table "public"."categorias_productos" to "authenticated";

grant select on table "public"."categorias_productos" to "authenticated";

grant trigger on table "public"."categorias_productos" to "authenticated";

grant truncate on table "public"."categorias_productos" to "authenticated";

grant update on table "public"."categorias_productos" to "authenticated";

grant delete on table "public"."categorias_productos" to "service_role";

grant insert on table "public"."categorias_productos" to "service_role";

grant references on table "public"."categorias_productos" to "service_role";

grant select on table "public"."categorias_productos" to "service_role";

grant trigger on table "public"."categorias_productos" to "service_role";

grant truncate on table "public"."categorias_productos" to "service_role";

grant update on table "public"."categorias_productos" to "service_role";

grant delete on table "public"."categorias_proveedor" to "anon";

grant insert on table "public"."categorias_proveedor" to "anon";

grant references on table "public"."categorias_proveedor" to "anon";

grant select on table "public"."categorias_proveedor" to "anon";

grant trigger on table "public"."categorias_proveedor" to "anon";

grant truncate on table "public"."categorias_proveedor" to "anon";

grant update on table "public"."categorias_proveedor" to "anon";

grant delete on table "public"."categorias_proveedor" to "authenticated";

grant insert on table "public"."categorias_proveedor" to "authenticated";

grant references on table "public"."categorias_proveedor" to "authenticated";

grant select on table "public"."categorias_proveedor" to "authenticated";

grant trigger on table "public"."categorias_proveedor" to "authenticated";

grant truncate on table "public"."categorias_proveedor" to "authenticated";

grant update on table "public"."categorias_proveedor" to "authenticated";

grant delete on table "public"."categorias_proveedor" to "service_role";

grant insert on table "public"."categorias_proveedor" to "service_role";

grant references on table "public"."categorias_proveedor" to "service_role";

grant select on table "public"."categorias_proveedor" to "service_role";

grant trigger on table "public"."categorias_proveedor" to "service_role";

grant truncate on table "public"."categorias_proveedor" to "service_role";

grant update on table "public"."categorias_proveedor" to "service_role";

grant delete on table "public"."conceptos_factura" to "anon";

grant insert on table "public"."conceptos_factura" to "anon";

grant references on table "public"."conceptos_factura" to "anon";

grant select on table "public"."conceptos_factura" to "anon";

grant trigger on table "public"."conceptos_factura" to "anon";

grant truncate on table "public"."conceptos_factura" to "anon";

grant update on table "public"."conceptos_factura" to "anon";

grant delete on table "public"."conceptos_factura" to "authenticated";

grant insert on table "public"."conceptos_factura" to "authenticated";

grant references on table "public"."conceptos_factura" to "authenticated";

grant select on table "public"."conceptos_factura" to "authenticated";

grant trigger on table "public"."conceptos_factura" to "authenticated";

grant truncate on table "public"."conceptos_factura" to "authenticated";

grant update on table "public"."conceptos_factura" to "authenticated";

grant delete on table "public"."conceptos_factura" to "service_role";

grant insert on table "public"."conceptos_factura" to "service_role";

grant references on table "public"."conceptos_factura" to "service_role";

grant select on table "public"."conceptos_factura" to "service_role";

grant trigger on table "public"."conceptos_factura" to "service_role";

grant truncate on table "public"."conceptos_factura" to "service_role";

grant update on table "public"."conceptos_factura" to "service_role";

grant delete on table "public"."empresas" to "anon";

grant insert on table "public"."empresas" to "anon";

grant references on table "public"."empresas" to "anon";

grant select on table "public"."empresas" to "anon";

grant trigger on table "public"."empresas" to "anon";

grant truncate on table "public"."empresas" to "anon";

grant update on table "public"."empresas" to "anon";

grant delete on table "public"."empresas" to "authenticated";

grant insert on table "public"."empresas" to "authenticated";

grant references on table "public"."empresas" to "authenticated";

grant select on table "public"."empresas" to "authenticated";

grant trigger on table "public"."empresas" to "authenticated";

grant truncate on table "public"."empresas" to "authenticated";

grant update on table "public"."empresas" to "authenticated";

grant delete on table "public"."empresas" to "service_role";

grant insert on table "public"."empresas" to "service_role";

grant references on table "public"."empresas" to "service_role";

grant select on table "public"."empresas" to "service_role";

grant trigger on table "public"."empresas" to "service_role";

grant truncate on table "public"."empresas" to "service_role";

grant update on table "public"."empresas" to "service_role";

grant delete on table "public"."factura_cargos" to "anon";

grant insert on table "public"."factura_cargos" to "anon";

grant references on table "public"."factura_cargos" to "anon";

grant select on table "public"."factura_cargos" to "anon";

grant trigger on table "public"."factura_cargos" to "anon";

grant truncate on table "public"."factura_cargos" to "anon";

grant update on table "public"."factura_cargos" to "anon";

grant delete on table "public"."factura_cargos" to "authenticated";

grant insert on table "public"."factura_cargos" to "authenticated";

grant references on table "public"."factura_cargos" to "authenticated";

grant select on table "public"."factura_cargos" to "authenticated";

grant trigger on table "public"."factura_cargos" to "authenticated";

grant truncate on table "public"."factura_cargos" to "authenticated";

grant update on table "public"."factura_cargos" to "authenticated";

grant delete on table "public"."factura_cargos" to "service_role";

grant insert on table "public"."factura_cargos" to "service_role";

grant references on table "public"."factura_cargos" to "service_role";

grant select on table "public"."factura_cargos" to "service_role";

grant trigger on table "public"."factura_cargos" to "service_role";

grant truncate on table "public"."factura_cargos" to "service_role";

grant update on table "public"."factura_cargos" to "service_role";

grant delete on table "public"."factura_conceptos" to "anon";

grant insert on table "public"."factura_conceptos" to "anon";

grant references on table "public"."factura_conceptos" to "anon";

grant select on table "public"."factura_conceptos" to "anon";

grant trigger on table "public"."factura_conceptos" to "anon";

grant truncate on table "public"."factura_conceptos" to "anon";

grant update on table "public"."factura_conceptos" to "anon";

grant delete on table "public"."factura_conceptos" to "authenticated";

grant insert on table "public"."factura_conceptos" to "authenticated";

grant references on table "public"."factura_conceptos" to "authenticated";

grant select on table "public"."factura_conceptos" to "authenticated";

grant trigger on table "public"."factura_conceptos" to "authenticated";

grant truncate on table "public"."factura_conceptos" to "authenticated";

grant update on table "public"."factura_conceptos" to "authenticated";

grant delete on table "public"."factura_conceptos" to "service_role";

grant insert on table "public"."factura_conceptos" to "service_role";

grant references on table "public"."factura_conceptos" to "service_role";

grant select on table "public"."factura_conceptos" to "service_role";

grant trigger on table "public"."factura_conceptos" to "service_role";

grant truncate on table "public"."factura_conceptos" to "service_role";

grant update on table "public"."factura_conceptos" to "service_role";

grant delete on table "public"."factura_impuestos" to "anon";

grant insert on table "public"."factura_impuestos" to "anon";

grant references on table "public"."factura_impuestos" to "anon";

grant select on table "public"."factura_impuestos" to "anon";

grant trigger on table "public"."factura_impuestos" to "anon";

grant truncate on table "public"."factura_impuestos" to "anon";

grant update on table "public"."factura_impuestos" to "anon";

grant delete on table "public"."factura_impuestos" to "authenticated";

grant insert on table "public"."factura_impuestos" to "authenticated";

grant references on table "public"."factura_impuestos" to "authenticated";

grant select on table "public"."factura_impuestos" to "authenticated";

grant trigger on table "public"."factura_impuestos" to "authenticated";

grant truncate on table "public"."factura_impuestos" to "authenticated";

grant update on table "public"."factura_impuestos" to "authenticated";

grant delete on table "public"."factura_impuestos" to "service_role";

grant insert on table "public"."factura_impuestos" to "service_role";

grant references on table "public"."factura_impuestos" to "service_role";

grant select on table "public"."factura_impuestos" to "service_role";

grant trigger on table "public"."factura_impuestos" to "service_role";

grant truncate on table "public"."factura_impuestos" to "service_role";

grant update on table "public"."factura_impuestos" to "service_role";

grant delete on table "public"."factura_items" to "anon";

grant insert on table "public"."factura_items" to "anon";

grant references on table "public"."factura_items" to "anon";

grant select on table "public"."factura_items" to "anon";

grant trigger on table "public"."factura_items" to "anon";

grant truncate on table "public"."factura_items" to "anon";

grant update on table "public"."factura_items" to "anon";

grant delete on table "public"."factura_items" to "authenticated";

grant insert on table "public"."factura_items" to "authenticated";

grant references on table "public"."factura_items" to "authenticated";

grant select on table "public"."factura_items" to "authenticated";

grant trigger on table "public"."factura_items" to "authenticated";

grant truncate on table "public"."factura_items" to "authenticated";

grant update on table "public"."factura_items" to "authenticated";

grant delete on table "public"."factura_items" to "service_role";

grant insert on table "public"."factura_items" to "service_role";

grant references on table "public"."factura_items" to "service_role";

grant select on table "public"."factura_items" to "service_role";

grant trigger on table "public"."factura_items" to "service_role";

grant truncate on table "public"."factura_items" to "service_role";

grant update on table "public"."factura_items" to "service_role";

grant delete on table "public"."facturas" to "anon";

grant insert on table "public"."facturas" to "anon";

grant references on table "public"."facturas" to "anon";

grant select on table "public"."facturas" to "anon";

grant trigger on table "public"."facturas" to "anon";

grant truncate on table "public"."facturas" to "anon";

grant update on table "public"."facturas" to "anon";

grant delete on table "public"."facturas" to "authenticated";

grant insert on table "public"."facturas" to "authenticated";

grant references on table "public"."facturas" to "authenticated";

grant select on table "public"."facturas" to "authenticated";

grant trigger on table "public"."facturas" to "authenticated";

grant truncate on table "public"."facturas" to "authenticated";

grant update on table "public"."facturas" to "authenticated";

grant delete on table "public"."facturas" to "service_role";

grant insert on table "public"."facturas" to "service_role";

grant references on table "public"."facturas" to "service_role";

grant select on table "public"."facturas" to "service_role";

grant trigger on table "public"."facturas" to "service_role";

grant truncate on table "public"."facturas" to "service_role";

grant update on table "public"."facturas" to "service_role";

grant delete on table "public"."formas_pago" to "anon";

grant insert on table "public"."formas_pago" to "anon";

grant references on table "public"."formas_pago" to "anon";

grant select on table "public"."formas_pago" to "anon";

grant trigger on table "public"."formas_pago" to "anon";

grant truncate on table "public"."formas_pago" to "anon";

grant update on table "public"."formas_pago" to "anon";

grant delete on table "public"."formas_pago" to "authenticated";

grant insert on table "public"."formas_pago" to "authenticated";

grant references on table "public"."formas_pago" to "authenticated";

grant select on table "public"."formas_pago" to "authenticated";

grant trigger on table "public"."formas_pago" to "authenticated";

grant truncate on table "public"."formas_pago" to "authenticated";

grant update on table "public"."formas_pago" to "authenticated";

grant delete on table "public"."formas_pago" to "service_role";

grant insert on table "public"."formas_pago" to "service_role";

grant references on table "public"."formas_pago" to "service_role";

grant select on table "public"."formas_pago" to "service_role";

grant trigger on table "public"."formas_pago" to "service_role";

grant truncate on table "public"."formas_pago" to "service_role";

grant update on table "public"."formas_pago" to "service_role";

grant delete on table "public"."ia_procesamientos" to "anon";

grant insert on table "public"."ia_procesamientos" to "anon";

grant references on table "public"."ia_procesamientos" to "anon";

grant select on table "public"."ia_procesamientos" to "anon";

grant trigger on table "public"."ia_procesamientos" to "anon";

grant truncate on table "public"."ia_procesamientos" to "anon";

grant update on table "public"."ia_procesamientos" to "anon";

grant delete on table "public"."ia_procesamientos" to "authenticated";

grant insert on table "public"."ia_procesamientos" to "authenticated";

grant references on table "public"."ia_procesamientos" to "authenticated";

grant select on table "public"."ia_procesamientos" to "authenticated";

grant trigger on table "public"."ia_procesamientos" to "authenticated";

grant truncate on table "public"."ia_procesamientos" to "authenticated";

grant update on table "public"."ia_procesamientos" to "authenticated";

grant delete on table "public"."ia_procesamientos" to "service_role";

grant insert on table "public"."ia_procesamientos" to "service_role";

grant references on table "public"."ia_procesamientos" to "service_role";

grant select on table "public"."ia_procesamientos" to "service_role";

grant trigger on table "public"."ia_procesamientos" to "service_role";

grant truncate on table "public"."ia_procesamientos" to "service_role";

grant update on table "public"."ia_procesamientos" to "service_role";

grant delete on table "public"."pagos" to "anon";

grant insert on table "public"."pagos" to "anon";

grant references on table "public"."pagos" to "anon";

grant select on table "public"."pagos" to "anon";

grant trigger on table "public"."pagos" to "anon";

grant truncate on table "public"."pagos" to "anon";

grant update on table "public"."pagos" to "anon";

grant delete on table "public"."pagos" to "authenticated";

grant insert on table "public"."pagos" to "authenticated";

grant references on table "public"."pagos" to "authenticated";

grant select on table "public"."pagos" to "authenticated";

grant trigger on table "public"."pagos" to "authenticated";

grant truncate on table "public"."pagos" to "authenticated";

grant update on table "public"."pagos" to "authenticated";

grant delete on table "public"."pagos" to "service_role";

grant insert on table "public"."pagos" to "service_role";

grant references on table "public"."pagos" to "service_role";

grant select on table "public"."pagos" to "service_role";

grant trigger on table "public"."pagos" to "service_role";

grant truncate on table "public"."pagos" to "service_role";

grant update on table "public"."pagos" to "service_role";

grant delete on table "public"."producto_aliases" to "anon";

grant insert on table "public"."producto_aliases" to "anon";

grant references on table "public"."producto_aliases" to "anon";

grant select on table "public"."producto_aliases" to "anon";

grant trigger on table "public"."producto_aliases" to "anon";

grant truncate on table "public"."producto_aliases" to "anon";

grant update on table "public"."producto_aliases" to "anon";

grant delete on table "public"."producto_aliases" to "authenticated";

grant insert on table "public"."producto_aliases" to "authenticated";

grant references on table "public"."producto_aliases" to "authenticated";

grant select on table "public"."producto_aliases" to "authenticated";

grant trigger on table "public"."producto_aliases" to "authenticated";

grant truncate on table "public"."producto_aliases" to "authenticated";

grant update on table "public"."producto_aliases" to "authenticated";

grant delete on table "public"."producto_aliases" to "service_role";

grant insert on table "public"."producto_aliases" to "service_role";

grant references on table "public"."producto_aliases" to "service_role";

grant select on table "public"."producto_aliases" to "service_role";

grant trigger on table "public"."producto_aliases" to "service_role";

grant truncate on table "public"."producto_aliases" to "service_role";

grant update on table "public"."producto_aliases" to "service_role";

grant delete on table "public"."productos" to "anon";

grant insert on table "public"."productos" to "anon";

grant references on table "public"."productos" to "anon";

grant select on table "public"."productos" to "anon";

grant trigger on table "public"."productos" to "anon";

grant truncate on table "public"."productos" to "anon";

grant update on table "public"."productos" to "anon";

grant delete on table "public"."productos" to "authenticated";

grant insert on table "public"."productos" to "authenticated";

grant references on table "public"."productos" to "authenticated";

grant select on table "public"."productos" to "authenticated";

grant trigger on table "public"."productos" to "authenticated";

grant truncate on table "public"."productos" to "authenticated";

grant update on table "public"."productos" to "authenticated";

grant delete on table "public"."productos" to "service_role";

grant insert on table "public"."productos" to "service_role";

grant references on table "public"."productos" to "service_role";

grant select on table "public"."productos" to "service_role";

grant trigger on table "public"."productos" to "service_role";

grant truncate on table "public"."productos" to "service_role";

grant update on table "public"."productos" to "service_role";

grant delete on table "public"."proveedores" to "anon";

grant insert on table "public"."proveedores" to "anon";

grant references on table "public"."proveedores" to "anon";

grant select on table "public"."proveedores" to "anon";

grant trigger on table "public"."proveedores" to "anon";

grant truncate on table "public"."proveedores" to "anon";

grant update on table "public"."proveedores" to "anon";

grant delete on table "public"."proveedores" to "authenticated";

grant insert on table "public"."proveedores" to "authenticated";

grant references on table "public"."proveedores" to "authenticated";

grant select on table "public"."proveedores" to "authenticated";

grant trigger on table "public"."proveedores" to "authenticated";

grant truncate on table "public"."proveedores" to "authenticated";

grant update on table "public"."proveedores" to "authenticated";

grant delete on table "public"."proveedores" to "service_role";

grant insert on table "public"."proveedores" to "service_role";

grant references on table "public"."proveedores" to "service_role";

grant select on table "public"."proveedores" to "service_role";

grant trigger on table "public"."proveedores" to "service_role";

grant truncate on table "public"."proveedores" to "service_role";

grant update on table "public"."proveedores" to "service_role";

grant delete on table "public"."remito_items" to "anon";

grant insert on table "public"."remito_items" to "anon";

grant references on table "public"."remito_items" to "anon";

grant select on table "public"."remito_items" to "anon";

grant trigger on table "public"."remito_items" to "anon";

grant truncate on table "public"."remito_items" to "anon";

grant update on table "public"."remito_items" to "anon";

grant delete on table "public"."remito_items" to "authenticated";

grant insert on table "public"."remito_items" to "authenticated";

grant references on table "public"."remito_items" to "authenticated";

grant select on table "public"."remito_items" to "authenticated";

grant trigger on table "public"."remito_items" to "authenticated";

grant truncate on table "public"."remito_items" to "authenticated";

grant update on table "public"."remito_items" to "authenticated";

grant delete on table "public"."remito_items" to "service_role";

grant insert on table "public"."remito_items" to "service_role";

grant references on table "public"."remito_items" to "service_role";

grant select on table "public"."remito_items" to "service_role";

grant trigger on table "public"."remito_items" to "service_role";

grant truncate on table "public"."remito_items" to "service_role";

grant update on table "public"."remito_items" to "service_role";

grant delete on table "public"."remitos" to "anon";

grant insert on table "public"."remitos" to "anon";

grant references on table "public"."remitos" to "anon";

grant select on table "public"."remitos" to "anon";

grant trigger on table "public"."remitos" to "anon";

grant truncate on table "public"."remitos" to "anon";

grant update on table "public"."remitos" to "anon";

grant delete on table "public"."remitos" to "authenticated";

grant insert on table "public"."remitos" to "authenticated";

grant references on table "public"."remitos" to "authenticated";

grant select on table "public"."remitos" to "authenticated";

grant trigger on table "public"."remitos" to "authenticated";

grant truncate on table "public"."remitos" to "authenticated";

grant update on table "public"."remitos" to "authenticated";

grant delete on table "public"."remitos" to "service_role";

grant insert on table "public"."remitos" to "service_role";

grant references on table "public"."remitos" to "service_role";

grant select on table "public"."remitos" to "service_role";

grant trigger on table "public"."remitos" to "service_role";

grant truncate on table "public"."remitos" to "service_role";

grant update on table "public"."remitos" to "service_role";


  create policy "Lectura para usuarios autenticados"
  on "public"."categorias_productos"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Usuarios autenticados pueden leer categorias_productos"
  on "public"."categorias_productos"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Lectura para usuarios autenticados"
  on "public"."categorias_proveedor"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Lectura para usuarios autenticados"
  on "public"."empresas"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Insertar items de factura para usuarios autenticados"
  on "public"."factura_items"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Lectura para usuarios autenticados"
  on "public"."factura_items"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Insertar facturas para usuarios autenticados"
  on "public"."facturas"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Lectura para usuarios autenticados"
  on "public"."facturas"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Lectura para usuarios autenticados"
  on "public"."formas_pago"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Usuarios autenticados pueden actualizar logs IA"
  on "public"."ia_procesamientos"
  as permissive
  for update
  to authenticated
using (true)
with check (true);



  create policy "Usuarios autenticados pueden crear logs IA"
  on "public"."ia_procesamientos"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Usuarios autenticados pueden ver logs IA"
  on "public"."ia_procesamientos"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Lectura para usuarios autenticados"
  on "public"."pagos"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Usuarios autenticados pueden actualizar pagos"
  on "public"."pagos"
  as permissive
  for update
  to authenticated
using (true)
with check (true);



  create policy "Usuarios autenticados pueden borrar pagos"
  on "public"."pagos"
  as permissive
  for delete
  to authenticated
using (true);



  create policy "Usuarios autenticados pueden insertar pagos"
  on "public"."pagos"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Actualizar productos para usuarios autenticados"
  on "public"."productos"
  as permissive
  for update
  to authenticated
using (true)
with check (true);



  create policy "Crear productos para usuarios autenticados"
  on "public"."productos"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Lectura para usuarios autenticados"
  on "public"."productos"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Actualizar proveedores para usuarios autenticados"
  on "public"."proveedores"
  as permissive
  for update
  to authenticated
using (true)
with check (true);



  create policy "Insertar proveedores para usuarios autenticados"
  on "public"."proveedores"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Lectura para usuarios autenticados"
  on "public"."proveedores"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Insertar items de remito para usuarios autenticados"
  on "public"."remito_items"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Lectura para usuarios autenticados"
  on "public"."remito_items"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Insertar remitos para usuarios autenticados"
  on "public"."remitos"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Lectura para usuarios autenticados"
  on "public"."remitos"
  as permissive
  for select
  to authenticated
using (true);



